### ISSUE TITLE
TypeError: Cannot read property 'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by binarykitchen** [Open-Xchange-Frontend/generator-ox-ui-module#10]
This error came up when I tried to lay out the boilerplate for first time:

```
/Users/michael-heuberger/code/smx/appsuite-theme-test ❯❯❯ ./node_modules/.bin/yo ox-ui-module
    force .yo-rc.json
TypeError: Cannot read property 'hasOwnProperty' of undefined
    at OxUiModuleGenerator.end (/Users/michael-heuberger/code/smx/appsuite-theme-test/node_modules/generator-ox-ui-module/generators/app/index.js:85:83)
    at Object.<anonymous> (/Users/michael-heuberger/code/smx/appsuite-theme-test/node_modules/yeoman-generator/lib/index.js:751:25)
    at /Users/michael-heuberger/code/smx/appsuite-theme-test/node_modules/run-async/index.js:47:25
    at new Promise (<anonymous>)
    at /Users/michael-heuberger/code/smx/appsuite-theme-test/node_modules/run-async/index.js:24:19
    at runLoop.add.taskCompleted (/Users/michael-heuberger/code/smx/appsuite-theme-test/node_modules/yeoman-generator/lib/index.js:752:11)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)
```

**Comment by binarykitchen** [comment]
Installed the latest versions of

``
    "generator-ox-ui-module": "0.17.2",
    "yo": "3.1.1"
```
